

- name: get instance metadata
  ec2_facts:

- name: install packages
  become: yes
  apt:
    name: "{{ item }}"
  with_items:
    - build-essential
    - libssl-dev
    - libffi-dev
    - python-dev
    - python-pip
    - ruby

- name: install gems
  gem:
    name: "{{ item }}"
  with_items:
    - rcredstash

- name: install credstash
  become: yes
  pip:
    name: credstash

- name: copy ruby-app.rb
  copy:
    src: files/ruby-app.rb
    dest: "{{ app_install_path }}"
    mode: 0700
  notify:
    - restart ruby-app

- name: copy ruby-app service
  become: yes
  template:
    src: templates/ruby-app.service.j2
    dest: "{{ app_service_path }}"
  notify:
    - restart ruby-app

- name: start/enable ruby-app
  become: yes
  systemd:
    name: ruby-app
    state: started
    enabled: yes
    daemon_reload: yes
    masked: no
