---

region: "{{ lookup('ENV','AWS_DEFAULT_REGION') }}"
profile: "{{ lookup('ENV','AWS_DEFAULT_PROFILE') }}"

ec2_keypair: credstash-demo
ec2_instance_type: t2.nano
kms_key_alias: alias/credstash
credstash_table: credential-store
instance_profile: credstash-demo
ec2_security_group: credstash-demo

# For convenience, secrets are provided unencrypted below.
# Not recommended outside of testing this demo.
credstash_secrets:
  - name: demo_secret_1
    value: aerobic-uneven-genius
    env: demo
  - name: demo_secret_2
    value: revving-fissure-rage
    env: demo
  - name: production_secret
    value: 09hj8Sn834jkc0Df
    env: prod
