
- name: create iam role
  iam:
    iam_type: role
    name: "{{ instance_profile }}"
    state: present
    profile: "{{ profile }}"
    region: "{{ region }}"

- name: add policy to allow access to credstash
  iam_policy:
    state: present
    iam_type: role
    iam_name: "{{ instance_profile }}"
    policy_name: "credstash-demo-context"
    policy_json: "{{ lookup( 'template', 'instance_profile.json.j2') }}"
    profile: "{{ profile }}"
    region: "{{ region }}"
