
- name: install packages
  become: yes
  apt:
    name: "{{ item }}"
  with_items:
    - build-essential
    - libssl-dev
    - libffi-dev
    - python-dev
    - python-pip
    - ruby

- name: install credstash
  become: yes
  pip:
    name: credstash
